# Generated by Django 4.0.5 on 2022-06-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
